//
//  Copyright 2012 Christopher Dudley
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
#ifndef _CONFIG_H_
#define _CONFIG_H_

/*
 *  This header defines macros representing features present in the compiler.
 *  At the moment, this is mostly used to determine C++11 support.
 *
 *  In the future, this file could be generated by the compilation script after
 *  tests are run on the compiler to determine its feature set.
 */

// Check if we have C++11 support

#if __cplusplus >= 201103L
    #ifndef _HAS_CPP_11
        #define _HAS_CPP_11
    #endif
#endif

// This has absolutely no effect in c++, so we include it just to make sure we
// have some stuff defined by the standard library implementation
#include <ciso646>

// Detect if we are using libc++
#ifdef _LIBCPP_VERSION
#define _HAS_LIBCXX
#endif

// clang feature check macro compatibility for gcc
#ifndef __has_feature
    #define __has_feature(x) 0              // Compatibility with non-clang compilers
#endif
#ifndef __has_extention
    #define __has_extention __has_feature   // Compatibility with pre-3.0 compilers
#endif

// Have a macro for determining the version of GCC we're using.
// This is 0 if we're not compiling with GCC
#ifdef __GNUC__
    #define GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__ )
#else
    #define GCC_VERSION 0
#endif // If we're compiling with GCC

// C++11 features
//
// All of the options are surrounded by ifndef checks so that external checks
// for the presence of C++11 options can be used to override this.
#ifdef _HAS_CPP_11
    #ifndef _HAS_STD_HASH
        #define _HAS_STD_HASH
    #endif

    #ifndef _HAS_STD_SWAP
        #define _HAS_STD_SWAP
    #endif

    #ifndef _HAS_DECLTYPE
        #define _HAS_DECLTYPE
    #endif

    #ifndef _HAS_AUTO
        #define _HAS_AUTO
    #endif

    // libstdc++ specific check.
    // If _GLIBCXX_USE_NANOSLEEP is not defined, this_thread::sleep_for and
    // this_thread::sleep_until are not declared in <thread>, even though they
    // are required by the C++11 Standard. If libstdc++ is configured with the
    // flag --enable-libstdcxx-time, the configure script will check for the
    // existence of the nanosleep function and, if found, define this macro.
    // However, most distributions don't seem to configure libstc++ with this
    // option, so the macro is almost never defined. This only changes things
    // in the header, so defining it yourself on a system that has nanosleep
    // will work, but is an extremely ugly and non-portable hack.
    //
    // For more information, see this post on StackOverflow:
    // http://stackoverflow.com/questions/12523122/what-is-glibcxx-use-nanosleep-all-about
    //
    // libc++ doesn't have this problem, so define the macros if we detect we are
    // using libc++

    #ifndef _HAS_SLEEP_FOR
        #if defined( _GLIBCXX_USE_NANOSLEEP )
            #define _HAS_SLEEP_FOR
        #elif defined( _HAS_LIBCXX )
            #define _HAS_SLEEP_FOR
        #endif // _GLIBCXX_USE_NANOSLEEP
    #endif // _HAS_SLEEP_FOR

    #ifndef _HAS_SLEEP_UNTIL
        #if defined( _GLIBCXX_USE_NANOSLEEP )
            #define _HAS_SLEEP_UNTIL
        #elif defined( _HAS_LIBCXX )
            #define _HAS_SLEEP_FOR
        #endif // _GLIBCXX_USE_NANOSLEEP
    #endif // _HAS_SLEEP_UNTIL

    #ifndef _HAS_STD_RANDOM
        #define _HAS_STD_RANDOM
    #endif // _HAS_STD_RANDOM

    #ifndef _HAS_OVERRIDE
        #define _HAS_OVERRIDE
    #endif // _HAS_OVERRIDE

    #ifndef _HAS_CONSTEXPR
        #define _HAS_CONSTEXPR
    #endif // _HAS_CONSTEXPR

    #ifndef _HAS_THREAD_LOCAL
        // Currently GCC 4.7 doesn't support thread_local, so check specifically for it.
        #if __has_extention(cxx_thread_local)
            #define _HAS_THREAD_LOCAL
        #elif GCC_VERSION >= 40800L // GCC 4.8+ has thread_local
            #define _HAS_THREAD_LOCAL
        #endif // has thread_local
    #endif // _HAS_THREAD_LOCAL

#endif//_HAS_CPP_11

#ifdef _HAS_THREAD_LOCAL
    #define THREAD_LOCAL thread_local
#else
    // Use __thread and hope it works.
    #define THREAD_LOCAL __thread
#endif // _HAS_THREAD_LOCAL

// Whether or not we support the override specifier for method declarations
#ifdef _HAS_OVERRIDE
    #define OVERRIDE_SPEC override
#else
    #define OVERRIDE_SPEC
#endif // _HAS_OVERRIDE

#ifdef _HAS_CONSTEXPR
    #define CONSTEXPR constexpr
#else
    #define CONSTEXPR
#endif // _HAS_CONSTEXPR

#endif//_CONFIG_H_
